"""initial_schema

Revision ID: d7aa04850c70
Revises: 
Create Date: 2026-04-22 13:16:58.446418

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd7aa04850c70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_text', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('reversibility', sa.String(length=30), nullable=False),
    sa.Column('time_sensitivity', sa.Integer(), nullable=False),
    sa.Column('preparedness', sa.Integer(), nullable=False),
    sa.Column('values_alignment', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.String(length=30), nullable=False),
    sa.Column('inaction_regret', sa.Integer(), nullable=False),
    sa.Column('action_regret_short', sa.Integer(), nullable=False),
    sa.Column('historical_pattern', sa.String(length=20), nullable=False),
    sa.Column('support_system', sa.Integer(), nullable=False),
    sa.Column('expected_growth', sa.Integer(), nullable=False),
    sa.Column('social_influence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('short_term_regret', sa.Integer(), nullable=False),
    sa.Column('long_term_regret', sa.Integer(), nullable=False),
    sa.Column('action_regret_raw', sa.Integer(), nullable=False),
    sa.Column('inaction_regret_raw', sa.Integer(), nullable=False),
    sa.Column('likely_regret_type', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('top_drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_summary', sa.Text(), nullable=False),
    sa.Column('future_you_message', sa.Text(), nullable=False),
    sa.Column('reflection_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_decision_id'), 'results', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_decision_id'), table_name='results')
    op.drop_table('results')
    op.drop_table('decisions')
    # ### end Alembic commands ###
